name: Release

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v2.1.0
      - run: docker build . -t vishklearning/nodeapp
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run: docker push vishklearning/nodeapp
      
    
